### PR TITLE
Adds Smooth Timers

### PR DESCRIPTION
**Pull request by 0xv1n**
This PR modifies the animation code for TimerBars to smooth them rather than do partial bar progress updates once per second.

### CODE REVIEW

**Comment by kauffman12** [comment]
I've added this with some small changes in 2.1.60.

**Comment by 0xv1n** [comment]
@kauffman12 would you be willing to add your dev branch to github? Would like to contribute but it feels bad wasting time writing code only to have a PR closed because it is already added on a non-visible branch.

**Comment by kauffman12** [comment]
Most the time I just pick a few issues to address over the course of a day and work in a local branch. There isn't currently a develop branch. This one just ended up needing some more changes. If you'd rather be the one to make them I can post all the comments on the PR and leave it open.

**Comment by 0xv1n** [comment]
No worries, if there's anything I can potentially work on let me know - would love to help out even though the parser is pretty much stable.

**Pull request closed without merging**
